service: content-bott

provider:
  name: aws
  runtime: java8
  memorySize: 1536
  timeout: 300
  region: eu-west-1

package:
  artifact: build/distributions/content-bot.zip

functions:
  answer:
    handler: contentbot.LambdaHandler
    events:
     - http:
         path: question
         method: post