service: content-bott

provider:
  name: aws
  runtime: java8
  memorySize: 1536
  timeout: 300
  region: eu-west-1
  iamRoleStatements:
   - Effect: Allow
     Action:
     - s3:getObject
     Resource: "arn:aws:s3:::newsticker-audio-files"
   - Effect: Allow
     Action:
     - lambda:InvokeFunction
     Resource: "arn:aws:lambda:eu-west-1:933782373565:function:polly-dev-text2speech"

package:
  artifact: build/distributions/content-bot.zip

functions:
  answer:
    handler: contentbot.GoogleActionLambdaHandler
    events:
     - http:
         path: question
         method: post

  filegenerator:
    handler: contentbot.AudioFileGeneratorHandler
    events:
    - schedule: rate(2 hours)